{
 "title": "SLO Overview",
 "tags": [ "slo" ],
 "panels": [
  {
   "title": "⬆️ 1d target",
   "type": "stat",
   "description": "The number of SLIs that are meeting their SLO objective in the last 1d",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n\t\t(\n\t\t  sum by (grafana_slo_uuid) (sum_over_time((grafana_slo_success_rate_5m < +Inf)[1d:5m]))\n\t\t  / sum by (grafana_slo_uuid) (sum_over_time((grafana_slo_total_rate_5m < +Inf)[1d:5m]))\n\t\t  # combine with series that aren't producing grafana_slo_success_rate_5m and grafana_slo_total_rate_5m\n\t\t  or avg by (grafana_slo_uuid) (grafana_slo_sli_1d)\n\t\t)\n\t\t> on(grafana_slo_uuid) grafana_slo_objective\n\t  ) OR on() vector(0)\n\t  ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "⬆️ 6h target",
   "type": "stat",
   "description": "The number of SLIs that are meeting their SLO objective in the last 6h",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n\t\t(\n\t\t  sum by (grafana_slo_uuid) (sum_over_time((grafana_slo_success_rate_5m < +Inf)[6h:5m]))\n\t\t  / sum by (grafana_slo_uuid) (sum_over_time((grafana_slo_total_rate_5m < +Inf)[6h:5m]))\n\t\t  # combine with series that aren't producing grafana_slo_success_rate_5m and grafana_slo_total_rate_5m\n\t\t  or avg by (grafana_slo_uuid) (grafana_slo_sli_6h)\n\t\t)\n\t\t> on(grafana_slo_uuid) grafana_slo_objective\n\t  ) OR on() vector(0)\n\t  ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "⬆️ 1h target",
   "type": "stat",
   "description": "The number of SLIs that are meeting their SLO objective in the last 1h",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n\t\t(\n\t\t  sum by (grafana_slo_uuid) (sum_over_time((grafana_slo_success_rate_5m < +Inf)[1h:5m]))\n\t\t  / sum by (grafana_slo_uuid) (sum_over_time((grafana_slo_total_rate_5m < +Inf)[1h:5m]))\n\t\t  # combine with series that aren't producing grafana_slo_success_rate_5m and grafana_slo_total_rate_5m\n\t\t  or avg by (grafana_slo_uuid) (grafana_slo_sli_1h)\n\t\t)\n\t\t> on(grafana_slo_uuid) grafana_slo_objective\n\t  ) OR on() vector(0)\n\t  ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SLO count",
   "type": "stat",
   "description": "The number of SLOs that are recording values",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (grafana_slo_uuid)(grafana_slo_sli_5m)) OR on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SLI series",
   "type": "stat",
   "description": "The total number of series created by SLO recording rules.",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count({__name__=~\"grafana_slo_.*\", grafana_slo_uuid!=\"\"}) OR on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "description": "SLO name with hyperlink to the SLO's dashboard",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "options": {
    "content": "#### [LGTM: HTTP Requests Success Rate](/d/grafana_slo_app-8b3nxmkoqbx47f7g1tu43?${__url_time_range})"
   }
  },
  {
   "title": "28d SLI",
   "type": "stat",
   "description": "Service level indicator's value over the last 28d",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(\nsum(sum_over_time((grafana_slo_success_rate_5m{grafana_slo_uuid=\"8b3nxmkoqbx47f7g1tu43\"} < +Inf)[28d:5m]))\n/ sum(sum_over_time((grafana_slo_total_rate_5m{grafana_slo_uuid=\"8b3nxmkoqbx47f7g1tu43\"} < +Inf)[28d:5m])), 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Budget left",
   "type": "stat",
   "description": "The unspent error budget over the last {0.995 28d} Window",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n\t\tclamp_max(sum(sum_over_time((grafana_slo_success_rate_5m{grafana_slo_uuid=\"8b3nxmkoqbx47f7g1tu43\"} < +Inf)[28d:5m]))\n\t\t/ sum(sum_over_time((grafana_slo_total_rate_5m{grafana_slo_uuid=\"8b3nxmkoqbx47f7g1tu43\"} < +Inf)[28d:5m])), 1)\n\t\t- on() grafana_slo_objective{grafana_slo_uuid=\"8b3nxmkoqbx47f7g1tu43\"}\n\t)\n\t/ on () (1 - grafana_slo_objective{grafana_slo_uuid=\"8b3nxmkoqbx47f7g1tu43\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SLI",
   "type": "timeseries",
   "description": "Service level indicator",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "clamp_max(sum(sum_over_time((grafana_slo_success_rate_5m{grafana_slo_uuid=\"8b3nxmkoqbx47f7g1tu43\"} < +Inf)[$__interval:]))\n/ sum(sum_over_time((grafana_slo_total_rate_5m{grafana_slo_uuid=\"8b3nxmkoqbx47f7g1tu43\"} < +Inf)[$__interval:])), 1)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}